services:
  - type: web
    name: safesphere-backend
    rootDir: Backend
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: FEATHERLESS_API_KEY
        sync: false
      - key: FEATHERLESS_MODEL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: WHISPER_MODEL
        value: tiny
